### ISSUE TITLE
NullPointerException at runtime in UserLocGrid constructor

### ISSUE THREAD

**Issue by LukeEarly** [LukeEarly/MyBattleshipRepo#1]
What happens when I run it:   The bold and italic are my responses in the program. 

Welcome to MyBattleshipGame! There are five difficulty levels to choose from: 
    1. Easy: 5 x 5 with 3 small ships, each 2 units long. 
    2. Medium: 10 x 10 with 4 medium-sized ships, each 3 units long. 
    3. Hard: 15 x 15 with 5 large ships, each 4 units long. 
    4. Harder: 20 x 20 with 6 huge ships, each 5 units long. 
    5. Hardest: 25 x 25 with 7 titanic ships, each 8 units long. 
Which level do you want to play on? **_1_**

This will walk you through placing your ships. Each one is 2 units long and can only be horizontal or vertical, not diagonal. 
What direction will your first ship be pointing ('v' or 'h' for vertical or horizontal)?**_h_**
What are the upper-leftmost coordinates it will include? **_a1_**
Exception in thread "main" java.lang.NullPointerException
	at UserLocGrid.<init>(UserLocGrid.java:65)
	at GameLaunch.main(GameLaunch.java:55)

Process finished with exit code 1

Screenshot:
![nullpointerexceptionissue](https://user-images.githubusercontent.com/23438839/34322585-bf5b4666-e7f8-11e7-9670-64c8544ec5cc.png)

**Comment by LukeEarly** [comment]
Variable wasn't initialized properly.
